# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 새벽 코딩
email: silee9019@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  현재는 1DP를 진행하는 과정을 기록하는 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://atmost1815.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: atmost1815

timezone: Asia/Seoul

# Build settings
highlighter:
markdown: kramdown
